export const GET_ALL_CONTINENT_MUTATION_KEY = ['get-all-continent-mutation-key']
export const GET_ALL_CONTINENT_QUERY_KEY = ['get-all-continent-query-key']
export const GET_ALL_COUNTRY_QUERY_KEY = ['get-all-country-query-key']
export const GET_COUNTIRES_BY_CONTINENT_MUTATION_KEY = ['get-countries-by-continent-mututation-key']
export const GET_COUNTRY_DETAILS_QUERY_KEY = ['get-country-details-query-key']